# Generated by Django 3.1.4 on 2020-12-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='manufacture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacture', verbose_name='manufacture'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='model'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('name', 'manufacture')},
        ),
    ]
