# Generated by Django 3.1.4 on 2020-12-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201206_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Body',
                'verbose_name_plural': 'Bodys',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuel types',
            },
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'Manufacture', 'verbose_name_plural': 'Manufactures'},
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('name', 'manufacture'), name='unique model of manufacture'),
        ),
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.body', verbose_name='body'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.fueltype', verbose_name='fuel type'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='model'),
        ),
    ]
