# Generated by Django 3.1.4 on 2020-12-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201207_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacture', verbose_name='manufacture'),
        ),
    ]
