# Generated by Django 3.1.4 on 2020-12-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201208_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.body', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fueltype', verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='model'),
        ),
    ]
